DROP TABLE SITES_INFO CASCADE CONSTRAINTS PURGE; 
DROP SEQUENCE SITES_INFO_SitesID;

CREATE SEQUENCE SITES_INFO_SitesID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE TABLE SITES_INFO (
    SiteID int NOT NULL ,
    SiteIP varchar2(255) NOT NULL UNIQUE,
    SiteAddress varchar2(255) NOT NULL UNIQUE,
    SiteStatus varchar2(255) DEFAULT 'INACTIVE',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SiteID)
);

SELECT * FROM SITES_INFO;


--SELECT * FROM DBA_DB_LINKS ;

--INSERT INTO SITES_INFO  (SiteID, SiteIP, SiteAddress) VALUES (SITES_INFO_SITESID.nextval, '192.168.123.128', 'example.com' );

--DELETE FROM SITES_INFO WHERE SiteID = 1;


COMMIT;