DROP TABLE SITES_LOG CASCADE CONSTRAINTS; 

CREATE TABLE SITES_LOG (
    LogId int NOT NULL ,
    requestedPath varchar2(255) NOT NULL ,
    responseCode int DEFAULT 500,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LogId)
);

SELECT * FROM SITES_LOG;

COMMIT;