CREATE OR REPLACE TRIGGER TR_AFT_INS_SITES_INFO 
AFTER INSERT 
ON SITES_INFO
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;    
	q  VARCHAR2(500):= '';
    linkName VARCHAR2(10):= '';
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10));
    DBMS_OUTPUT.PUT_LINE('New Data inserted, Value is - ');
    DBMS_OUTPUT.PUT_LINE(CHR(10));
    DBMS_OUTPUT.PUT_LINE( :NEW.SiteID  || ' -- ' ||  :NEW.SiteIP || ' -- ' ||  :NEW.SiteAddress );
    
    AddSitePack.createDBLink(:NEW.SiteID ,:NEW.SiteIP, '12345', 1622);
    DBMS_OUTPUT.PUT_LINE(CHR(10));
    DBMS_OUTPUT.PUT_LINE('Data link created successfully');
    DBMS_OUTPUT.PUT_LINE(CHR(10));
    
	
	AddSitePack.siteIntoSubs(:NEW.SiteID);
	DBMS_OUTPUT.PUT_LINE(CHR(10));
    DBMS_OUTPUT.PUT_LINE('Site Is SUBSCRIBED FOR CACHE');
    DBMS_OUTPUT.PUT_LINE(CHR(10));
--    execute immediate 'select * from dual@site1';
    
    COMMIT;
END;
/


CREATE OR REPLACE TRIGGER TR_BFR_UP_SITES_INFO 
BEFORE UPDATE
ON SITES_INFO
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;    
BEGIN
    :NEW.UpdatedAt := systimestamp;
    COMMIT;
END;
/

CREATE OR REPLACE TRIGGER TR_AFT_INS_SITES_SUBS_CACHE
AFTER INSERT
ON SITES_SUBSCRIBE_CACHE
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;    
BEGIN
	DBMS_OUTPUT.PUT_LINE(CHR(10));
    DBMS_OUTPUT.PUT_LINE('Site Is SUBSCRIBED FOR CACHE TRIGGER CALL');
    DBMS_OUTPUT.PUT_LINE(CHR(10));
END;
/


